-- gitstate consolidated baseline schema.
-- Generated by folding the original incremental migrations into one clean file.
-- Forward-only; idempotent (IF NOT EXISTS) where the originals were.

-- ╔═ from 20260618_001_init.sql ═════════════════════════════════════════════
-- 20260618_001_init
-- Base schema: identity, multi-tenant orgs (RLS), work/git, metrics, billing, audit.
-- forward-only; a rollback is a new migration.

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS citext;     -- case-insensitive email

-- ── RLS helper ───────────────────────────────────────────────────────────
-- Request middleware runs each tx with: SET LOCAL app.current_org = '<uuid>'.
-- Policies compare against current_setting('app.current_org', true) so a missing
-- value yields NULL (no rows) rather than an error.
CREATE OR REPLACE FUNCTION current_org() RETURNS uuid
  LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.current_org', true), '')::uuid $$;

-- ── Identity ─────────────────────────────────────────────────────────────
CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email         citext UNIQUE NOT NULL,
    name          text,
    avatar_url    text,
    password_hash text,                       -- null when OAuth-only
    is_super_admin boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE oauth_accounts (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider      text NOT NULL,              -- google | microsoft | github | gitlab
    provider_uid  text NOT NULL,
    email         citext,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_uid)
);

-- Rotating refresh tokens with reuse-detection via family_id.
CREATE TABLE refresh_tokens (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    family_id     uuid NOT NULL,
    token_hash    text NOT NULL UNIQUE,
    replaced_by   uuid REFERENCES refresh_tokens(id),
    revoked_at    timestamptz,
    expires_at    timestamptz NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON refresh_tokens (user_id);
CREATE INDEX ON refresh_tokens (family_id);

-- ── Tenancy ──────────────────────────────────────────────────────────────
CREATE TABLE organizations (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug          citext UNIQUE NOT NULL,
    name          text NOT NULL,
    plan_key      text NOT NULL DEFAULT 'free',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- role: owner | admin | member (=builder, billable) | stakeholder (FREE per wedge P6)
CREATE TABLE org_members (
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role          text NOT NULL DEFAULT 'member',
    created_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (org_id, user_id)
);
CREATE INDEX ON org_members (user_id);

CREATE TABLE org_invites (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    email         citext NOT NULL,
    role          text NOT NULL DEFAULT 'member',
    token_hash    text NOT NULL UNIQUE,
    expires_at    timestamptz NOT NULL,
    accepted_at   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- ── Repos & work ─────────────────────────────────────────────────────────
CREATE TABLE repos (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    platform      text NOT NULL,              -- github | gitlab
    external_id   text NOT NULL,
    full_name     text NOT NULL,              -- owner/name
    default_branch text,
    clone_url     text,
    last_synced_at timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, platform, external_id)
);
CREATE INDEX ON repos (org_id);

CREATE TABLE projects (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name          text NOT NULL,
    key           text,                       -- short code
    archived      boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON projects (org_id);

-- Two truth-modes (decisions P1): source = 'git' (derived) | 'native' (manual).
CREATE TABLE issues (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id    uuid REFERENCES projects(id) ON DELETE SET NULL,
    repo_id       uuid REFERENCES repos(id) ON DELETE SET NULL,
    source        text NOT NULL DEFAULT 'native',  -- git | native
    platform      text,                            -- github | gitlab (when source=git)
    external_id   text,
    number        int,
    title         text NOT NULL,
    body          text,
    state         text NOT NULL DEFAULT 'open',     -- open | in_progress | done | closed
    derived_state text,                             -- computed from linked git activity
    assignee_id   uuid REFERENCES users(id),
    labels        text[] NOT NULL DEFAULT '{}',
    custom_fields jsonb NOT NULL DEFAULT '{}',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, platform, external_id)
);
CREATE INDEX ON issues (org_id);
CREATE INDEX ON issues (project_id);

CREATE TABLE pull_requests (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id       uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    platform      text NOT NULL,
    external_id   text NOT NULL,
    number        int,
    title         text,
    author_login  text,
    state         text,                              -- open | merged | closed
    additions     int,
    deletions     int,
    changed_files int,
    first_commit_at timestamptz,
    merged_at     timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, repo_id, external_id)
);
CREATE INDEX ON pull_requests (org_id);

CREATE TABLE commits (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id       uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    sha           text NOT NULL,
    author_login  text,
    author_email  citext,
    is_agent      boolean NOT NULL DEFAULT false,    -- agent vs human authored (decisions P5)
    message       text,
    additions     int,
    deletions     int,
    committed_at  timestamptz,
    UNIQUE (org_id, repo_id, sha)
);
CREATE INDEX ON commits (org_id);
CREATE INDEX ON commits (repo_id, committed_at);

-- Markdown plan-in-repo (roadmap.md / tasks/*.md) projected as work.
CREATE TABLE task_files (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id       uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    path          text NOT NULL,
    parsed        jsonb NOT NULL DEFAULT '{}',
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, repo_id, path)
);

-- ── Derived metrics ──────────────────────────────────────────────────────
CREATE TABLE effort_estimates (         -- LLM diff-difficulty (decisions P3)
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    pr_id         uuid REFERENCES pull_requests(id) ON DELETE CASCADE,
    issue_id      uuid REFERENCES issues(id) ON DELETE CASCADE,
    difficulty    numeric,                          -- model-judged
    rationale     text,
    evidence      jsonb NOT NULL DEFAULT '{}',      -- links to git evidence
    model         text,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON effort_estimates (org_id);

CREATE TABLE cycle_times (              -- DORA-style, observed from git
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    pr_id         uuid REFERENCES pull_requests(id) ON DELETE CASCADE,
    lead_time_secs bigint,                          -- first commit → merge
    review_secs   bigint,
    computed_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON cycle_times (org_id);

-- Involvement as TEXTURE (decisions P2) — never a single score.
CREATE TABLE involvement (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id    uuid REFERENCES projects(id) ON DELETE CASCADE,
    user_id       uuid REFERENCES users(id) ON DELETE SET NULL,
    period_start  date NOT NULL,
    features_shipped int NOT NULL DEFAULT 0,
    reviews_done  int NOT NULL DEFAULT 0,          -- counts the invisible work
    areas_owned   int NOT NULL DEFAULT 0,
    active        boolean NOT NULL DEFAULT true,
    dimensions    jsonb NOT NULL DEFAULT '{}',     -- extensible texture
    UNIQUE (org_id, project_id, user_id, period_start)
);
CREATE INDEX ON involvement (org_id);

-- Agent-native unit (decisions P5).
CREATE TABLE agent_runs (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id       uuid REFERENCES repos(id) ON DELETE SET NULL,
    goal          text,
    diff_summary  jsonb NOT NULL DEFAULT '{}',
    tests_passed  boolean,
    human_action  text,                            -- accepted | edited | reverted
    iterations    int,
    cost_usd      numeric,
    supervisor_id uuid REFERENCES users(id),
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON agent_runs (org_id);

-- ── Billing (EE) ─────────────────────────────────────────────────────────
CREATE TABLE plans (
    key           text PRIMARY KEY,
    name          text NOT NULL,
    usd_cents     int NOT NULL DEFAULT 0,           -- price defined in USD
    builders      int NOT NULL DEFAULT 0,
    max_conns     int NOT NULL DEFAULT 0,           -- CEILING not reservation
    features      jsonb NOT NULL DEFAULT '{}'
);

CREATE TABLE subscriptions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    plan_key      text NOT NULL REFERENCES plans(key),
    status        text NOT NULL DEFAULT 'active',   -- active | past_due | canceled
    current_period_end timestamptz,
    paystack_sub_code text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id)
);

CREATE TABLE usage_events (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    kind          text NOT NULL,                    -- builder_seat | llm_tokens | sync | ...
    quantity      numeric NOT NULL DEFAULT 0,
    cost_usd      numeric NOT NULL DEFAULT 0,
    occurred_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON usage_events (org_id, occurred_at);

-- USD↔ZAR rates captured at charge time (decisions A8).
CREATE TABLE exchange_rates (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    base          text NOT NULL,                    -- USD
    quote         text NOT NULL,                    -- ZAR
    rate          numeric NOT NULL,
    provider      text,
    fetched_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON exchange_rates (base, quote, fetched_at DESC);

CREATE TABLE invoices (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    status        text NOT NULL DEFAULT 'draft',    -- draft | open | paid | void
    usd_cents     int NOT NULL DEFAULT 0,           -- billed in USD
    zar_cents     int,                              -- charged in ZAR
    fx_rate       numeric,                          -- rate used at capture
    fx_rate_id    uuid REFERENCES exchange_rates(id),
    period_start  date,
    period_end    date,
    paystack_ref  text,
    issued_at     timestamptz,
    paid_at       timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON invoices (org_id);

CREATE TABLE invoice_lines (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id    uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    description   text NOT NULL,
    usd_cents     int NOT NULL DEFAULT 0,
    evidence      jsonb NOT NULL DEFAULT '{}',      -- git-backed; gaps flagged (decisions P4)
    is_estimated  boolean NOT NULL DEFAULT false
);

CREATE TABLE payments (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    invoice_id    uuid REFERENCES invoices(id) ON DELETE SET NULL,
    zar_cents     int NOT NULL,
    status        text NOT NULL,                    -- success | failed | pending
    paystack_ref  text,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE paystack_events (          -- webhook idempotency (decisions S4)
    id            text PRIMARY KEY,                 -- paystack event id
    type          text NOT NULL,
    payload       jsonb NOT NULL,
    processed_at  timestamptz NOT NULL DEFAULT now()
);

-- ── Platform ─────────────────────────────────────────────────────────────
CREATE TABLE audit_log (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id      uuid REFERENCES users(id),
    org_id        uuid REFERENCES organizations(id),
    action        text NOT NULL,
    target        text,
    meta          jsonb NOT NULL DEFAULT '{}',
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON audit_log (org_id, created_at);

CREATE TABLE feature_flags (
    key           text PRIMARY KEY,
    enabled       boolean NOT NULL DEFAULT false,
    meta          jsonb NOT NULL DEFAULT '{}'
);

-- ── Row-Level Security (decisions A2/S1) ─────────────────────────────────
-- Enable RLS + an org-scoping policy on every org-scoped table.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'repos','projects','issues','pull_requests','commits','task_files',
    'effort_estimates','cycle_times','involvement','agent_runs',
    'subscriptions','usage_events','invoices','payments'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org())
        WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- Seed plans (mirror config.example.yaml ladder).
INSERT INTO plans (key, name, usd_cents, builders, max_conns) VALUES
  ('free',  'Free',        0,     2,   10),
  ('hobby', 'Hobby',       900,   5,   25),
  ('pro',   'Pro',         3900,  15,  75),
  ('team',  'Team',        19900, 50,  200),
  ('scale', 'Scale',       24900, 100, 400),
  ('ent',   'Enterprise',  0,     0,   0)
ON CONFLICT (key) DO NOTHING;

-- ╔═ from 20260618_002_capacity.sql ═════════════════════════════════════════════
-- 20260618_002_capacity
-- forward-only; a rollback is a new migration.
--
-- Adds org-scoped capacity/availability/PTO/time-tracking tables (Wave 4 D4).
-- Decisions:
--   A2/S1 — RLS via current_org() on every org-scoped table.
--   P1    — time_entries.source = 'git' | 'manual' (two truth-modes).
--   A4    — forward-only; rollback = new migration.

-- ── Leave entries (PTO / sick / holidays) ────────────────────────────────
CREATE TABLE leave_entries (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind        text NOT NULL DEFAULT 'pto',       -- pto | sick | holiday
    start_date  date NOT NULL,
    end_date    date NOT NULL,
    status      text NOT NULL DEFAULT 'pending',   -- pending | approved | rejected
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT leave_entries_kind_check   CHECK (kind   IN ('pto','sick','holiday')),
    CONSTRAINT leave_entries_status_check CHECK (status IN ('pending','approved','rejected')),
    CONSTRAINT leave_entries_dates_check  CHECK (end_date >= start_date)
);
CREATE INDEX ON leave_entries (org_id);
CREATE INDEX ON leave_entries (org_id, user_id);
CREATE INDEX ON leave_entries (org_id, start_date, end_date);

-- ── Availability (per-member working hours / days per week) ──────────────
-- A row is effective from effective_from until superseded by a later row for
-- the same (org_id, user_id).  The most-recent row wins.
CREATE TABLE availability (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    weekly_hours    numeric NOT NULL DEFAULT 40,   -- hours per week the member is available
    working_days    int[]   NOT NULL DEFAULT '{1,2,3,4,5}', -- ISO weekdays: 1=Mon…7=Sun
    effective_from  date    NOT NULL DEFAULT CURRENT_DATE,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT availability_weekly_hours_check CHECK (weekly_hours > 0 AND weekly_hours <= 168),
    CONSTRAINT availability_working_days_check CHECK (array_length(working_days, 1) BETWEEN 1 AND 7)
);
CREATE INDEX ON availability (org_id);
CREATE INDEX ON availability (org_id, user_id, effective_from DESC);

-- ── Time entries (git-derived or manually entered) ───────────────────────
-- source = 'git'    → derived from git activity (commits/PRs); stub hook, primary path is manual.
-- source = 'manual' → entered by the user; the explicit "truth gap" required by decisions P1/P4.
CREATE TABLE time_entries (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    issue_id    uuid REFERENCES issues(id) ON DELETE SET NULL,  -- optional link
    source      text NOT NULL DEFAULT 'manual',    -- git | manual (decisions P1)
    minutes     int  NOT NULL,                     -- duration logged
    occurred_on date NOT NULL DEFAULT CURRENT_DATE,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT time_entries_source_check  CHECK (source  IN ('git','manual')),
    CONSTRAINT time_entries_minutes_check CHECK (minutes > 0)
);
CREATE INDEX ON time_entries (org_id);
CREATE INDEX ON time_entries (org_id, user_id);
CREATE INDEX ON time_entries (org_id, occurred_on);

-- ── Row-Level Security (decisions A2/S1) ─────────────────────────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'leave_entries',
    'availability',
    'time_entries'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org())
        WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260618_003_repo_tokens.sql ═════════════════════════════════════════════
-- 20260618_003_repo_tokens
-- forward-only; a rollback is a new migration.
--
-- Adds token_encrypted (bytea) to repos so that connected-repo access tokens
-- can be persisted encrypted at rest (AES-256-GCM via internal/crypto) instead
-- of being re-supplied by the client on every sync call.
--
-- The column is nullable: existing rows keep NULL until a token is explicitly
-- stored via store.SetRepoToken. The old in-memory / re-supply path remains
-- fully functional while this column is NULL.

ALTER TABLE repos
  ADD COLUMN IF NOT EXISTS token_encrypted bytea;

-- ╔═ from 20260618_004_per_builder_pricing.sql ═════════════════════════════════════════════
-- 20260618_004_per_builder_pricing
-- Per-BUILDER tier model (validated by cmd/billsim, now canonical).
-- Stakeholders are always free (decisions P6). LLM: included per-builder allowance,
-- overage billed at provider-cost × overage_markup; BYOK → $0. Bill USD (decisions A8).
-- forward-only; a rollback is a new migration.

-- New per-builder pricing columns on plans. usd_cents is kept for back-compat
-- (set to 0 for per-builder tiers).
ALTER TABLE plans
  ADD COLUMN IF NOT EXISTS per_builder_cents int     NOT NULL DEFAULT 0,  -- monthly price per billable builder
  ADD COLUMN IF NOT EXISTS included_llm_cents int    NOT NULL DEFAULT 0,  -- included managed-LLM allowance per builder/mo (at our provider cost)
  ADD COLUMN IF NOT EXISTS overage_markup    numeric NOT NULL DEFAULT 1.0; -- markup on managed-LLM usage beyond the allowance

-- New ladder (builders = cap: free 2, others 0 = unlimited).
--   free       — $0/builder, ≤2 builders, BYOK-only (no managed allowance), scale-to-zero.
--   team       — $12/builder, $4/builder included LLM, overage ×1.30.
--   business   — $25/builder, $12/builder included LLM, overage ×1.30, + SSO/audit.
--   enterprise — custom (self-host / BYOK / unlimited).
INSERT INTO plans (key, name, usd_cents, per_builder_cents, included_llm_cents, overage_markup, builders, max_conns, features) VALUES
  ('free',       'Free',       0, 0,    0,    1.00, 2, 10,  '{"byok_only": true, "scale_to_zero": true}'),
  ('team',       'Team',       0, 1200, 400,  1.30, 0, 0,   '{}'),
  ('business',   'Business',   0, 2500, 1200, 1.30, 0, 0,   '{"sso": true, "audit": true}'),
  ('enterprise', 'Enterprise', 0, 0,    0,    1.00, 0, 0,   '{"custom": true, "self_host": true, "byok": true, "unlimited": true}')
ON CONFLICT (key) DO UPDATE SET
  name               = EXCLUDED.name,
  usd_cents          = EXCLUDED.usd_cents,
  per_builder_cents  = EXCLUDED.per_builder_cents,
  included_llm_cents = EXCLUDED.included_llm_cents,
  overage_markup     = EXCLUDED.overage_markup,
  builders           = EXCLUDED.builders,
  max_conns          = EXCLUDED.max_conns,
  features           = EXCLUDED.features;

-- ╔═ from 20260618_005_platform_connections.sql ═════════════════════════════════════════════
-- 20260618_005_platform_connections
-- Per-org GitHub/GitLab app connections: stores the encrypted access token obtained
-- via the OAuth-app authorize flow so sync no longer re-supplies a PAT each time.
-- forward-only.

CREATE TABLE platform_connections (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    platform        text NOT NULL,                 -- github | gitlab
    connected_by    uuid REFERENCES users(id) ON DELETE SET NULL,
    external_login  text,                           -- the connected account login/username
    token_encrypted bytea,                          -- AES-256-GCM encrypted access token (internal/crypto)
    refresh_encrypted bytea,                        -- optional encrypted refresh token (gitlab)
    scopes          text,
    expires_at      timestamptz,
    base_url        text,                           -- gitlab self-hosted base, null for SaaS
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, platform)
);
CREATE INDEX ON platform_connections (org_id);

ALTER TABLE platform_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_connections FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON platform_connections
    USING (org_id = current_org())
    WITH CHECK (org_id = current_org());

-- ╔═ from 20260618_006_org_llm_settings.sql ═════════════════════════════════════════════
-- 20260618_006_org_llm_settings
-- Per-org LLM configuration: BYOK (bring your own provider key → $0 managed cost)
-- or managed (use the platform key, metered + billed as overage on the per-builder tier).
-- forward-only.

CREATE TABLE org_llm_settings (
    org_id            uuid PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    mode              text NOT NULL DEFAULT 'managed',  -- managed | byok
    provider          text NOT NULL DEFAULT 'anthropic',
    api_key_encrypted bytea,                            -- AES-256-GCM encrypted BYOK key (internal/crypto)
    model             text,                             -- optional override; falls back to config default
    updated_by        uuid REFERENCES users(id) ON DELETE SET NULL,
    updated_at        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE org_llm_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_llm_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON org_llm_settings
    USING (org_id = current_org())
    WITH CHECK (org_id = current_org());

-- ╔═ from 20260618_007_calendar_connections.sql ═════════════════════════════════════════════
-- 20260618_007_calendar_connections
-- Per-user Google / Microsoft calendar connections for two-way leave/availability sync:
--   push approved leave → calendar events; pull OOO/busy → availability.
-- forward-only.

CREATE TABLE calendar_connections (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id            uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id           uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider          text NOT NULL,              -- google | microsoft
    external_email    text,                        -- the connected calendar account
    calendar_id       text,                        -- target calendar (default 'primary')
    token_encrypted   bytea,                       -- AES-256-GCM access token (internal/crypto)
    refresh_encrypted bytea,                       -- AES-256-GCM refresh token
    scopes            text,
    expires_at        timestamptz,
    push_leave        boolean NOT NULL DEFAULT true,  -- push approved leave to this calendar
    pull_busy         boolean NOT NULL DEFAULT true,  -- pull OOO/busy into availability
    last_synced_at    timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, user_id, provider)
);
CREATE INDEX ON calendar_connections (org_id);
CREATE INDEX ON calendar_connections (user_id);

-- Link a leave entry to the calendar event we created, so updates/cancellations sync.
ALTER TABLE leave_entries
    ADD COLUMN IF NOT EXISTS calendar_event_id text,
    ADD COLUMN IF NOT EXISTS calendar_provider text;

ALTER TABLE calendar_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_connections FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON calendar_connections
    USING (org_id = current_org())
    WITH CHECK (org_id = current_org());

-- ╔═ from 20260618_008_leave_types_balances.sql ═════════════════════════════════════════════
-- 20260618_008_leave_types_balances
-- Richer leave management (inspired by dedicated leave tools): configurable leave
-- TYPES, per-user BALANCES (entitled / used / carried), and half-day support.
-- forward-only.

CREATE TABLE leave_types (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id           uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name             text NOT NULL,                 -- Vacation, Sick, Personal, Parental, …
    color            text NOT NULL DEFAULT '#2DD4BF',
    default_days     numeric NOT NULL DEFAULT 0,     -- annual entitlement default
    requires_approval boolean NOT NULL DEFAULT true,
    accrues          boolean NOT NULL DEFAULT false, -- accrue monthly vs granted up front
    carryover_max    numeric NOT NULL DEFAULT 0,     -- max days carried into next year
    paid             boolean NOT NULL DEFAULT true,
    archived         boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, name)
);
CREATE INDEX ON leave_types (org_id);

CREATE TABLE leave_balances (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    leave_type_id uuid NOT NULL REFERENCES leave_types(id) ON DELETE CASCADE,
    year          int  NOT NULL,
    entitled_days numeric NOT NULL DEFAULT 0,
    carried_days  numeric NOT NULL DEFAULT 0,
    used_days     numeric NOT NULL DEFAULT 0,        -- approved leave consumed
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, user_id, leave_type_id, year)
);
CREATE INDEX ON leave_balances (org_id);
CREATE INDEX ON leave_balances (user_id);

-- Link leave entries to a type and support half-days.
ALTER TABLE leave_entries
    ADD COLUMN IF NOT EXISTS leave_type_id uuid REFERENCES leave_types(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS half_day boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS portion  text NOT NULL DEFAULT 'full'; -- full | am | pm

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['leave_types','leave_balances'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260619_009_contribution.sql ═════════════════════════════════════════════
-- 20260619_009_contribution
-- "Dev contribution to outcomes" — configurable, evidence-backed, gaming-resistant.
-- v1 stores org-level dimension WEIGHTS (the profile itself is computed on demand from
-- commits/PRs/issues/involvement/effort_estimates/cycle_times). Blame-survival + SZZ
-- plug into the same model once real-repo sync exists.
-- forward-only.

CREATE TABLE contribution_weights (
    org_id     uuid PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    -- relative weights per dimension (any non-negative scale; normalized at read time).
    shipped    numeric NOT NULL DEFAULT 30,  -- merged PRs / issues closed / features shipped
    review     numeric NOT NULL DEFAULT 20,  -- reviews + collaboration (the invisible senior work)
    effort     numeric NOT NULL DEFAULT 20,  -- LLM-estimated difficulty (NOT lines of code)
    quality    numeric NOT NULL DEFAULT 15,  -- low revert/hotfix rate, healthy cycle time
    ownership  numeric NOT NULL DEFAULT 15,  -- areas owned / knowledge spread (bus-factor)
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE contribution_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE contribution_weights FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON contribution_weights
    USING (org_id = current_org())
    WITH CHECK (org_id = current_org());

-- ╔═ from 20260619_010_gitanalysis.sql ═════════════════════════════════════════════
-- 20260619_010_gitanalysis
-- Deep git analysis that powers the gaming-resistant contribution dimensions:
--   * commit_files     — per-commit file-level churn + test detection (test-coupling)
--   * author_survival  — git-blame line survival per author (durability: does your code persist?)
--   * bug_introductions— SZZ: blame bug-fix commits back to the change that introduced them (quality)
-- Populated by internal/gitanalysis (clones the repo, runs git log/blame/SZZ). Aggregates only;
-- no source code is stored. forward-only.

CREATE TABLE commit_files (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id     uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    commit_sha  text NOT NULL,
    author_email citext,
    path        text NOT NULL,
    additions   integer NOT NULL DEFAULT 0,
    deletions   integer NOT NULL DEFAULT 0,
    is_test     boolean NOT NULL DEFAULT false,
    committed_at timestamptz,
    UNIQUE (org_id, repo_id, commit_sha, path)
);
CREATE INDEX ON commit_files (org_id, repo_id);
CREATE INDEX ON commit_files (org_id, author_email);

CREATE TABLE author_survival (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id         uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    author_email    citext NOT NULL,
    surviving_lines integer NOT NULL DEFAULT 0, -- lines authored that still exist at HEAD
    authored_lines  integer NOT NULL DEFAULT 0, -- total lines this author ever introduced
    computed_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, repo_id, author_email)
);
CREATE INDEX ON author_survival (org_id);

CREATE TABLE bug_introductions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id        uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    author_email   citext NOT NULL,        -- who introduced the buggy line (SZZ blame)
    introduced_sha text NOT NULL,
    fix_sha        text NOT NULL,          -- the bug-fix commit that touched it
    lines          integer NOT NULL DEFAULT 1,
    detected_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, repo_id, introduced_sha, fix_sha)
);
CREATE INDEX ON bug_introductions (org_id);
CREATE INDEX ON bug_introductions (org_id, author_email);

-- New contribution dimension: durability (blame-survival). Default weight.
ALTER TABLE contribution_weights
    ADD COLUMN IF NOT EXISTS durability numeric NOT NULL DEFAULT 15;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['commit_files','author_survival','bug_introductions'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260619_011_invoicing.sql ═════════════════════════════════════════════
-- 20260619_011_invoicing
-- CLIENT invoicing DERIVED FROM GIT effort (the "…and the invoice" half of the wedge):
-- effort_estimates + merged PRs over a period → invoice line-items with git evidence,
-- shareable read-only via a token. Named client_* to avoid the existing billing `invoices`.
-- forward-only.

CREATE TABLE clients (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name          text NOT NULL,
    contact_email text,
    -- billing rate in USD cents per unit of effort (1 effort point ≈ one LLM-sized unit).
    rate_cents    integer NOT NULL DEFAULT 15000,
    notes         text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, name)
);
CREATE INDEX ON clients (org_id);

-- Optional link from a project to the client it bills to.
ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_id uuid REFERENCES clients(id) ON DELETE SET NULL;

CREATE TABLE client_invoices (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    client_id     uuid REFERENCES clients(id) ON DELETE SET NULL,
    project_id    uuid REFERENCES projects(id) ON DELETE SET NULL,
    number        text NOT NULL,                       -- human invoice number e.g. INV-2026-001
    status        text NOT NULL DEFAULT 'draft',       -- draft | sent | paid | void
    period_start  date NOT NULL,
    period_end    date NOT NULL,
    currency      text NOT NULL DEFAULT 'USD',
    subtotal_cents integer NOT NULL DEFAULT 0,
    total_cents   integer NOT NULL DEFAULT 0,
    share_token   text UNIQUE,                          -- public read-only link
    notes         text,
    issued_at     timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, number)
);
CREATE INDEX ON client_invoices (org_id);
CREATE INDEX ON client_invoices (org_id, status);

CREATE TABLE client_invoice_lines (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    invoice_id   uuid NOT NULL REFERENCES client_invoices(id) ON DELETE CASCADE,
    description  text NOT NULL,                         -- what was delivered
    effort_points numeric NOT NULL DEFAULT 0,           -- summed LLM effort estimate
    quantity     numeric NOT NULL DEFAULT 1,
    unit_rate_cents integer NOT NULL DEFAULT 0,
    amount_cents integer NOT NULL DEFAULT 0,
    evidence     jsonb NOT NULL DEFAULT '[]',           -- [{prTitle, repo, mergedAt, sha}] git proof
    sort         integer NOT NULL DEFAULT 0
);
CREATE INDEX ON client_invoice_lines (org_id, invoice_id);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['clients','client_invoices','client_invoice_lines'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260619_012_invoice_token_lookup.sql ═════════════════════════════════════════════
-- 20260619_012_invoice_token_lookup
-- The public (unauthenticated) invoice share view must resolve a share_token → org
-- BEFORE any org context exists, but client_invoices has RLS, so the app role can't
-- read it. A SECURITY DEFINER function (runs as the owner, bypassing RLS) resolves
-- exactly the one invoice for a given unguessable token, then the handler reads it
-- inside db.WithOrg(orgID). forward-only.

CREATE OR REPLACE FUNCTION client_invoice_org_by_token(tok text)
RETURNS TABLE(org_id uuid, invoice_id uuid)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT org_id, id
  FROM client_invoices
  WHERE share_token IS NOT NULL AND share_token = tok
  LIMIT 1
$$;

REVOKE ALL ON FUNCTION client_invoice_org_by_token(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION client_invoice_org_by_token(text) TO gitstate_app;

-- ╔═ from 20260619_013_notifications.sql ═════════════════════════════════════════════
-- 20260619_013_notifications
-- Notification channels + digest config: evidence-based weekly status, stale/blocked PRs,
-- who's OOO — delivered to Slack/webhook/email. forward-only.

CREATE TABLE notification_channels (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    kind        text NOT NULL,                 -- slack | webhook | email
    target      text NOT NULL,                 -- webhook URL or email address
    label       text,
    enabled     boolean NOT NULL DEFAULT true,
    -- which digests this channel receives, e.g. {"weeklyStatus":true,"stalePRs":true,"ooo":true}
    digests     jsonb NOT NULL DEFAULT '{"weeklyStatus":true,"stalePRs":true,"ooo":true}',
    schedule    text NOT NULL DEFAULT 'weekly', -- weekly | daily
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON notification_channels (org_id);

CREATE TABLE notification_log (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    channel_id  uuid REFERENCES notification_channels(id) ON DELETE SET NULL,
    kind        text NOT NULL,                 -- which digest
    status      text NOT NULL,                 -- sent | failed | preview
    summary     text,
    sent_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON notification_log (org_id, sent_at);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['notification_channels','notification_log'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260619_014_contribution_extras.sql ═════════════════════════════════════════════
-- 20260619_014_contribution_extras
-- Contribution over time (cached period snapshots), an advisory equity ledger
-- (suggested vs actual share informed by contribution), and peer kudos (the SPACE
-- "satisfaction" axis + a partial answer to reviewer collusion). forward-only.

CREATE TABLE contribution_snapshots (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    period_start date NOT NULL,
    period_end   date NOT NULL,
    composite    numeric NOT NULL DEFAULT 0,
    dimensions   jsonb NOT NULL DEFAULT '{}',   -- {shipped, review, effort, quality, ownership, durability}
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, user_id, period_start, period_end)
);
CREATE INDEX ON contribution_snapshots (org_id, period_start);

CREATE TABLE equity_allocations (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    period_start  date NOT NULL,
    period_end    date NOT NULL,
    -- advisory: % of the contribution-allocated pool suggested by the model
    suggested_pct numeric NOT NULL DEFAULT 0,
    -- what was actually granted (entered by an admin) — model is advisory only
    actual_pct    numeric,
    pool_label    text NOT NULL DEFAULT 'Contribution pool',
    note          text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, user_id, period_start, period_end)
);
CREATE INDEX ON equity_allocations (org_id);

CREATE TABLE kudos (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    from_user   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    dimension   text,                          -- optional: ties to a contribution axis
    message     text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON kudos (org_id, to_user);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['contribution_snapshots','equity_allocations','kudos'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260619_015_webhooks_deploys.sql ═════════════════════════════════════════════
-- 20260619_015_webhooks_deploys
-- Inbound webhooks (real-time sync) + CI/CD deployments → REAL DORA deploy-frequency
-- and MTTR (the two metrics git history alone can't give). forward-only.

-- Per-org webhook secret for verifying inbound GitHub/GitLab payload signatures.
CREATE TABLE webhook_configs (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    provider    text NOT NULL,                 -- github | gitlab
    secret      text NOT NULL,                 -- HMAC secret (GitHub) / token (GitLab)
    enabled     boolean NOT NULL DEFAULT true,
    last_event_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, provider)
);
CREATE INDEX ON webhook_configs (org_id);

CREATE TABLE deployments (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id      uuid REFERENCES repos(id) ON DELETE SET NULL,
    environment  text NOT NULL DEFAULT 'production',
    status       text NOT NULL DEFAULT 'success',  -- success | failure
    sha          text,
    source       text NOT NULL DEFAULT 'manual',   -- github_actions | gitlab_ci | manual
    external_id  text,
    deployed_at  timestamptz NOT NULL DEFAULT now(),
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, source, external_id)
);
CREATE INDEX ON deployments (org_id, deployed_at);
CREATE INDEX ON deployments (org_id, environment);

-- Incidents drive MTTR (opened on a failed deploy / reported, closed on recovery).
CREATE TABLE incidents (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id      uuid REFERENCES repos(id) ON DELETE SET NULL,
    title        text,
    opened_at    timestamptz NOT NULL DEFAULT now(),
    resolved_at  timestamptz,
    severity     text NOT NULL DEFAULT 'minor',
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON incidents (org_id);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['webhook_configs','deployments','incidents'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- Inbound webhooks resolve org from the secret BEFORE org context exists → needs an
-- RLS-bypassing lookup (same pattern as the public invoice token).
CREATE OR REPLACE FUNCTION webhook_org_by_secret(prov text, sec text)
RETURNS uuid LANGUAGE sql SECURITY DEFINER STABLE AS $$
  SELECT org_id FROM webhook_configs WHERE provider = prov AND secret = sec AND enabled LIMIT 1
$$;
REVOKE ALL ON FUNCTION webhook_org_by_secret(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION webhook_org_by_secret(text, text) TO gitstate_app;

-- ╔═ from 20260620_016_cheapest_pricing.sql ═════════════════════════════════════════════
-- 20260620_016_cheapest_pricing
-- Reprice so gitstate is the cheapest option at ANY team size.
-- Rationale: competitors price per SEAT and charge extra for AI. gitstate prices
-- per BUILDER (stakeholders free) with AI included. Setting Team to $6 managed
-- (AI included) beats the cheapest AI-inclusive competitor (Linear $8) even for a
-- pure-builder team; BYOK $3 (= $6 − $3 included-LLM) beats the cheapest no-AI
-- per-seat tool (GitHub Projects $3.67). With free stakeholders, gitstate wins at
-- every team shape. forward-only.

UPDATE plans SET per_builder_cents = 600,  included_llm_cents = 300  WHERE key = 'team';
UPDATE plans SET per_builder_cents = 1400, included_llm_cents = 600  WHERE key = 'business';

-- Managed LLM is metered at the model's EXACT standard rate — zero visible markup,
-- no per-seat AI tax. ALL of our margin is the bulk/committed-use discount we get
-- on tokens (~35%): we buy below list and charge list. So overage_markup = 1.00
-- (charge == list); the profit is purely the wholesale spread, never a markup.
UPDATE plans SET overage_markup = 1.00 WHERE key IN ('team','business');

-- ╔═ from 20260621_017_effort_calibration.sql ═════════════════════════════════════════════
-- 20260621_017_effort_calibration
-- Self-calibrating effort estimation (Wave 1 of the AI/agent flywheel).
--
-- Today effort_estimates stores the model's difficulty (1-10) but never links to
-- the ACTUAL outcome, so difficulty->hours is a fixed guess. This adds the
-- closed loop: store the calibrated prediction at creation, fill the real actual
-- (lead time) at merge, and maintain per-cohort difficulty->time curves so the
-- conversion learns from each org's own history. Forward-only.

-- Predictions + actuals on the estimate row.
ALTER TABLE effort_estimates
    ADD COLUMN IF NOT EXISTS predicted_secs numeric,  -- calibrated estimate at creation (difficulty->secs via curve)
    ADD COLUMN IF NOT EXISTS actual_secs    bigint,   -- observed lead time, filled at merge from cycle_times
    ADD COLUMN IF NOT EXISTS cohort_key     text,     -- cohort used for the conversion (repo / area / change-type)
    ADD COLUMN IF NOT EXISTS size_bucket    text,     -- xs|s|m|l|xl by LOC + files touched
    ADD COLUMN IF NOT EXISTS change_type    text;      -- feature|fix|refactor|chore|docs|test (heuristic)

-- Backfill linkage from observed cycle times for already-merged PRs is done in
-- Go (metrics) so the existing pr_id join stays in one place.

-- Per-org, per-cohort difficulty -> observed-actual-time curve. The richest
-- cohort with enough n wins (repo|area -> repo -> global), with empirical-Bayes
-- shrinkage toward the global prior when n is small (applied in Go at read time).
CREATE TABLE effort_calibration (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id            uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    cohort_key        text NOT NULL,          -- 'global' | 'repo:<id>' | 'repo:<id>|area:<path>' | 'type:<t>'
    difficulty_bucket int  NOT NULL,          -- 1..10 (rounded model difficulty)
    median_secs       bigint,                 -- recency-weighted median observed actual
    p25_secs          bigint,
    p75_secs          bigint,
    mean_secs         bigint,
    n                 int  NOT NULL DEFAULT 0, -- sample size in the cohort/bucket
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, cohort_key, difficulty_bucket)
);
CREATE INDEX ON effort_calibration (org_id, cohort_key);

-- Per-org running estimation-accuracy summary (MAE / bias), surfaced in the UI so
-- a team can see "estimates run 20% low on the payments service".
CREATE TABLE effort_accuracy (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    cohort_key   text NOT NULL,
    n            int  NOT NULL DEFAULT 0,
    mae_secs     bigint,                       -- mean absolute error
    bias_ratio   numeric,                      -- mean(predicted/actual): <1 = under-estimating
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, cohort_key)
);
CREATE INDEX ON effort_accuracy (org_id);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['effort_calibration','effort_accuracy'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format($p$CREATE POLICY org_isolation ON %I
        USING (org_id = current_org()) WITH CHECK (org_id = current_org());$p$, t);
  END LOOP;
END $$;

-- ╔═ from 20260621_018_api_tokens.sql ═════════════════════════════════════════════
-- 20260621_018_api_tokens
-- Scoped API tokens for agent/LLM integrations (Wave 2+ of the AI/agent flywheel).
-- A long-lived, hashed, scoped token lets the `gittrack` CLI, the issue-context
-- endpoint, and the MCP server authenticate a machine/agent against one org with
-- least-privilege scopes — separate from human JWT sessions. Forward-only.
--
-- The raw token (e.g. "gsk_<random>") is shown ONCE at creation; only its sha256
-- is stored. Pre-auth resolution (no org context yet) goes through a SECURITY
-- DEFINER function, mirroring webhook_org_by_secret / client_invoice_org_by_token.

CREATE TABLE api_tokens (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id      uuid REFERENCES users(id) ON DELETE SET NULL, -- creator (attribution)
    name         text NOT NULL,
    token_hash   text NOT NULL UNIQUE,        -- sha256(raw token); raw shown once
    prefix       text NOT NULL,               -- first chars for display (gsk_xxxx…)
    scopes       text[] NOT NULL DEFAULT '{}', -- e.g. read:issues, read:context, write:agent_runs, write:issues
    last_used_at timestamptz,
    expires_at   timestamptz,                 -- NULL = no expiry
    revoked_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON api_tokens (org_id);

ALTER TABLE api_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_tokens FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON api_tokens
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());

-- Pre-auth lookup: resolve org/user/scopes from a token hash, bypassing RLS (the
-- request has no org context yet). SECURITY DEFINER + locked down to the app role,
-- only returns a row for a live (non-revoked, non-expired) token.
CREATE OR REPLACE FUNCTION api_token_by_hash(p_hash text)
RETURNS TABLE (org_id uuid, user_id uuid, token_id uuid, scopes text[])
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
    SELECT t.org_id, t.user_id, t.id, t.scopes
    FROM api_tokens t
    WHERE t.token_hash = p_hash
      AND t.revoked_at IS NULL
      AND (t.expires_at IS NULL OR t.expires_at > now())
    LIMIT 1
$$;

REVOKE ALL ON FUNCTION api_token_by_hash(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api_token_by_hash(text) TO gitstate_app;

-- ╔═ from 20260621_019_agent_run_links.sql ═════════════════════════════════════════════
-- 20260621_019_agent_run_links
-- Wave 3 of the AI/agent flywheel: let a logged agent run link to the PR/issue it
-- produced and name the agent, so agent work is attributable and feeds the same
-- outcome signals (merged-PR cycle time) that calibrate future estimates.
-- Forward-only; all additive nullable columns (no backfill needed).

ALTER TABLE agent_runs
    ADD COLUMN IF NOT EXISTS pr_id      uuid REFERENCES pull_requests(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS issue_id   uuid REFERENCES issues(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS agent_name text,   -- e.g. 'claude-code', 'cursor', 'custom'
    ADD COLUMN IF NOT EXISTS branch     text;    -- branch the run worked on

CREATE INDEX IF NOT EXISTS agent_runs_pr_idx ON agent_runs (pr_id);
CREATE INDEX IF NOT EXISTS agent_runs_issue_idx ON agent_runs (issue_id);

-- ╔═ from 20260621_020_search.sql ═════════════════════════════════════════════
-- 20260621_020_search
-- Wave 4 of the AI/agent flywheel: full-text + fuzzy search over issues, PRs and
-- commits so an agent (via MCP / the API) can find work by meaning, not exact
-- keywords ("the flaky auth test issue"). Generated tsvector columns kept in sync
-- automatically + GIN indexes; pg_trgm enables typo-tolerant similarity ranking.
-- Forward-only; generated columns backfill existing rows on add.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE issues ADD COLUMN IF NOT EXISTS search_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))) STORED;
CREATE INDEX IF NOT EXISTS issues_search_idx ON issues USING gin (search_tsv);
CREATE INDEX IF NOT EXISTS issues_title_trgm_idx ON issues USING gin (title gin_trgm_ops);

ALTER TABLE pull_requests ADD COLUMN IF NOT EXISTS search_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(title,''))) STORED;
CREATE INDEX IF NOT EXISTS pull_requests_search_idx ON pull_requests USING gin (search_tsv);

ALTER TABLE commits ADD COLUMN IF NOT EXISTS search_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(message,''))) STORED;
CREATE INDEX IF NOT EXISTS commits_search_idx ON commits USING gin (search_tsv);

-- ╔═ from 20260621_021_embeddings.sql ═════════════════════════════════════════════
-- 20260621_021_embeddings
-- True vector search (pgvector) for issue discovery — the semantic layer over the
-- Wave-4 FTS. Issues carry an embedding produced by gitstate's embedder; search
-- fuses cosine similarity with full-text rank. The default embedder is local +
-- deterministic (no external dependency, works offline over real content); a
-- neural provider can be configured later. Forward-only.

CREATE EXTENSION IF NOT EXISTS vector;

-- 256-dim matches gitstate's built-in local embedder. A neural provider override
-- must produce the same dimension (or this column is re-migrated).
ALTER TABLE issues
    ADD COLUMN IF NOT EXISTS embedding       vector(256),
    ADD COLUMN IF NOT EXISTS embedding_model text,
    ADD COLUMN IF NOT EXISTS embedded_at     timestamptz;

-- HNSW cosine index for fast nearest-neighbour. Partial (only embedded rows).
CREATE INDEX IF NOT EXISTS issues_embedding_idx
    ON issues USING hnsw (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL;

-- ╔═ from 20260621_022_analytics_events.sql ═════════════════════════════════════════════
-- 20260621_022_analytics_events
-- Instance-wide product analytics for the (server-rendered, super-admin-only)
-- cloud operator console: signups, logins, page/api activity, enriched with
-- coarse geo. PRIVACY: the raw IP is never retained — only a salted hash (so
-- repeat visitors can be counted without storing PII) plus coarse geo (country/
-- region/city) resolved from an optional local MaxMind/db-ip database.
--
-- This is a GLOBAL table (not org-scoped): it is written by the app on auth/nav
-- events and read ONLY through the BYPASSRLS admin pool by the super-admin
-- console — never exposed on the org-scoped /api surface. Forward-only.

CREATE TABLE analytics_events (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    kind        text NOT NULL,              -- signup | login | login_failed | pageview | api | logout | …
    user_id     uuid REFERENCES users(id) ON DELETE SET NULL,
    org_id      uuid,                        -- optional; no FK so cross-org analytics stays simple
    path        text,
    method      text,
    status      int,
    ip_hash     text,                        -- sha256(ip + salt); raw IP never stored
    country     text,                        -- ISO-3166 alpha-2 (from geo), '' when unknown
    region      text,
    city        text,
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON analytics_events (created_at DESC);
CREATE INDEX ON analytics_events (kind, created_at DESC);
CREATE INDEX ON analytics_events (country);

-- ╔═ from 20260622_023_drop_equity.sql ═════════════════════════════════════════════
-- 20260622_023_drop_equity
-- The "Equity (advisory)" feature was removed from the product — gitstate
-- surfaces contribution DATA but does not itself recommend equity/ownership
-- splits. Drop the now-unused table. Forward-only.
DROP TABLE IF EXISTS equity_allocations;

-- ╔═ from 20260622_024_accounting.sql ═════════════════════════════════════════════
-- 20260622_024_accounting
-- Accounting integrations: invoices can be pushed to Xero / QuickBooks (OAuth) or
-- created manually. Mirrors calendar_connections (AES-256-GCM tokens via
-- internal/crypto, org-scoped, FORCE-RLS). Forward-only.

CREATE TABLE accounting_connections (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id            uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id           uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider          text NOT NULL,              -- xero | quickbooks
    external_org_id   text,                        -- Xero tenantId / QuickBooks realmId
    external_name     text,                        -- the connected company/org name
    token_encrypted   bytea,                       -- AES-256-GCM access token
    refresh_encrypted bytea,                       -- AES-256-GCM refresh token
    scopes            text,
    expires_at        timestamptz,
    last_synced_at    timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, provider)
);
CREATE INDEX ON accounting_connections (org_id);

-- Track an invoice that has been pushed to an external accounting system.
ALTER TABLE client_invoices
    ADD COLUMN IF NOT EXISTS external_provider text,  -- xero | quickbooks
    ADD COLUMN IF NOT EXISTS external_id       text,  -- invoice id in that system
    ADD COLUMN IF NOT EXISTS external_url       text; -- deep link to view it there

ALTER TABLE accounting_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting_connections FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON accounting_connections
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());

-- ╔═ from 20260622_025_perf_indexes.sql ═════════════════════════════════════════════
-- 20260622_025_perf_indexes
-- Performance: indexes on hot org-scoped lookups that were doing Seq Scans on
-- seeded data (verified via EXPLAIN ANALYZE: Seq Scan → Index/Bitmap Scan).
-- Forward-only; all IF NOT EXISTS.

-- cycle_times per-PR (every UpsertCycleTime delete + the context-bundle lead-time lateral)
CREATE INDEX IF NOT EXISTS cycle_times_org_id_pr_id_computed_at_idx
    ON cycle_times (org_id, pr_id, computed_at DESC);

-- effort_estimates per-PR / per-issue (GetEstimateForPR/Issue, context bundle, calibration)
CREATE INDEX IF NOT EXISTS effort_estimates_org_id_pr_id_created_at_idx
    ON effort_estimates (org_id, pr_id, created_at DESC);
CREATE INDEX IF NOT EXISTS effort_estimates_org_id_issue_id_created_at_idx
    ON effort_estimates (org_id, issue_id, created_at DESC);

-- pull_requests list by repo (hottest PR read: metrics, PR lists, sync)
CREATE INDEX IF NOT EXISTS pull_requests_repo_id_created_at_idx
    ON pull_requests (repo_id, created_at DESC);

-- issues list by repo (sync goroutine)
CREATE INDEX IF NOT EXISTS issues_org_id_repo_id_idx
    ON issues (org_id, repo_id);

-- ╔═ from 20260623_026_pr_reviews.sql ═════════════════════════════════════════════
-- 20260623_026_pr_reviews
-- PR review events fetched from GitHub/GitLab, so Involvement can show real
-- "reviews done" (the invisible senior work) instead of an empty column.
-- Org-scoped, FORCE-RLS. Forward-only.

CREATE TABLE pr_reviews (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    repo_id        uuid NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    pr_id          uuid NOT NULL REFERENCES pull_requests(id) ON DELETE CASCADE,
    reviewer_login text NOT NULL,
    state          text NOT NULL,            -- approved | changes_requested | commented | dismissed
    external_id    text,                      -- platform review id (idempotency)
    submitted_at   timestamptz NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (org_id, pr_id, reviewer_login, submitted_at)
);
CREATE INDEX ON pr_reviews (org_id, repo_id);
CREATE INDEX ON pr_reviews (org_id, reviewer_login);
CREATE INDEX ON pr_reviews (org_id, pr_id);

ALTER TABLE pr_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE pr_reviews FORCE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON pr_reviews
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());

